import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Download, Share2, Shield, TrendingUp, Compass, Sparkles } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";

const PersonaBadge = () => {
  return (
    <DashboardLayout>
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-2xl">
        <h1 className="font-heading text-3xl font-bold text-center">Your Persona Badge</h1>
        <p className="mt-1 text-center text-muted-foreground">Share your career identity with the world.</p>

        {/* Badge Card */}
        <div className="mt-8 rounded-3xl bg-cta-gradient p-1">
          <div className="rounded-[calc(1.5rem-4px)] bg-card p-8">
            <div className="text-center">
              <div className="mx-auto mb-4 flex h-20 w-20 items-center justify-center rounded-full bg-secondary">
                <span className="text-4xl">🧠</span>
              </div>
              <p className="text-xs font-semibold uppercase tracking-widest text-primary">Career Persona</p>
              <h2 className="mt-1 font-heading text-3xl font-bold">The Adaptive Builder</h2>
              <p className="text-sm text-muted-foreground">AI-Resilient Product Strategist Archetype</p>
            </div>

            <div className="mt-6 grid grid-cols-2 gap-4">
              <div className="rounded-xl bg-muted/50 p-4 text-center">
                <Shield className="mx-auto h-5 w-5 text-success" />
                <p className="mt-2 font-heading text-xl font-bold">24%</p>
                <p className="text-xs text-muted-foreground">AI Resilience Score</p>
              </div>
              <div className="rounded-xl bg-muted/50 p-4 text-center">
                <TrendingUp className="mx-auto h-5 w-5 text-primary" />
                <p className="mt-2 font-heading text-xl font-bold">96%</p>
                <p className="text-xs text-muted-foreground">Growth Index</p>
              </div>
              <div className="rounded-xl bg-muted/50 p-4 text-center">
                <Compass className="mx-auto h-5 w-5 text-primary" />
                <p className="mt-2 font-heading text-xl font-bold">AI Product Manager</p>
                <p className="text-xs text-muted-foreground">Future Role Path</p>
              </div>
              <div className="rounded-xl bg-muted/50 p-4 text-center">
                <Sparkles className="mx-auto h-5 w-5 text-warning" />
                <p className="mt-2 font-heading text-xl font-bold">Top 15%</p>
                <p className="text-xs text-muted-foreground">Career Velocity</p>
              </div>
            </div>

            <div className="mt-6 border-t border-border pt-4 text-center">
              <p className="text-xs text-muted-foreground">Generated by <span className="font-semibold text-primary">Futurefly</span></p>
            </div>
          </div>
        </div>

        {/* Export Options */}
        <div className="mt-6 flex flex-wrap justify-center gap-3">
          <Button className="gap-2 bg-cta-gradient">
            <Share2 className="h-4 w-4" /> Share on LinkedIn
          </Button>
          <Button variant="outline" className="gap-2">
            <Share2 className="h-4 w-4" /> Instagram Story
          </Button>
          <Button variant="outline" className="gap-2">
            <Download className="h-4 w-4" /> Download PNG
          </Button>
        </div>
      </motion.div>
    </DashboardLayout>
  );
};

export default PersonaBadge;
